import {
  Zap,
  Droplets,
  Hammer,
  Car,
  Thermometer,
  TreeDeciduous,
  Home,
  Scissors,
  Stethoscope,
  Heart,
  Scale,
  SprayCan,
  Dumbbell,
  Camera,
  Sparkles,
  Shield,
} from 'lucide-react';

export interface Industry {
  id: string;
  name: string;
  icon: typeof Zap;
  shortName: string;
  avgJobValue: number;
  missedCalls: number;
  closeRate: number;
  description: string;
  exampleScenario: string;
  exampleCustomer: string;
  questions: string[];
}

export const industries: Industry[] = [
  {
    id: 'electrician',
    name: 'Electricians',
    icon: Zap,
    shortName: 'Electrician',
    avgJobValue: 350,
    missedCalls: 25,
    closeRate: 70,
    description: 'Wiring, repairs, installations, and electrical inspections',
    exampleScenario: 'Customer calls about flickering lights and burning smell',
    exampleCustomer: 'Hi, I have flickering lights in my kitchen and a burning smell. Can someone come take a look?',
    questions: ['What type of electrical work do you need?', 'When did you first notice the issue?', 'Is this an emergency?'],
  },
  {
    id: 'plumber',
    name: 'Plumbers',
    icon: Droplets,
    shortName: 'Plumber',
    avgJobValue: 400,
    missedCalls: 30,
    closeRate: 75,
    description: 'Repairs, installations, drain cleaning, and emergency services',
    exampleScenario: 'Customer has a burst pipe emergency at 10pm',
    exampleCustomer: 'Help! I have water pouring from under my sink. I think a pipe burst!',
    questions: ['Where is the issue located?', 'Is the water currently flowing?', 'Have you shut off the main water supply?'],
  },
  {
    id: 'builder',
    name: 'Builders & Contractors',
    icon: Hammer,
    shortName: 'Builder',
    avgJobValue: 2500,
    missedCalls: 15,
    closeRate: 60,
    description: 'Renovations, extensions, new builds, and remodeling',
    exampleScenario: 'Customer wants a quote for kitchen renovation',
    exampleCustomer: 'Hi, I\'m looking to renovate my kitchen. New cabinets, countertops, the works. Can you give me a rough estimate?',
    questions: ['What type of project are you planning?', 'What\'s your approximate budget?', 'Do you have plans drawn up yet?'],
  },
  {
    id: 'mechanic',
    name: 'Auto Mechanics',
    icon: Car,
    shortName: 'Mechanic',
    avgJobValue: 280,
    missedCalls: 35,
    closeRate: 80,
    description: 'Repairs, maintenance, diagnostics, and inspections',
    exampleScenario: 'Customer\'s car won\'t start, needs diagnosis',
    exampleCustomer: 'My car won\'t start this morning. It\'s making a clicking sound when I turn the key. Can I bring it in?',
    questions: ['What\'s the year, make, and model?', 'What sounds or symptoms is it showing?', 'Is it currently driveable?'],
  },
  {
    id: 'hvac',
    name: 'HVAC Technicians',
    icon: Thermometer,
    shortName: 'HVAC',
    avgJobValue: 450,
    missedCalls: 40,
    closeRate: 70,
    description: 'Heating, cooling, installation, and emergency repairs',
    exampleScenario: 'Customer\'s AC stopped working during heatwave',
    exampleCustomer: 'My AC just stopped working and it\'s 95 degrees in here! Can someone come out today?',
    questions: ['Is it heating or cooling that\'s not working?', 'When did it stop?', 'Any strange noises or smells?'],
  },
  {
    id: 'landscaper',
    name: 'Landscapers',
    icon: TreeDeciduous,
    shortName: 'Landscaper',
    avgJobValue: 200,
    missedCalls: 20,
    closeRate: 65,
    description: 'Lawn care, design, maintenance, and tree services',
    exampleScenario: 'Customer needs regular lawn maintenance',
    exampleCustomer: 'I need someone to mow my lawn regularly. It\'s about half an acre. What would you charge?',
    questions: ['What\'s the approximate lot size?', 'What services do you need?', 'How often would you like service?'],
  },
  {
    id: 'real_estate',
    name: 'Real Estate Agents',
    icon: Home,
    shortName: 'Real Estate Agent',
    avgJobValue: 8000,
    missedCalls: 25,
    closeRate: 35,
    description: 'Property sales, purchases, valuations, and consultations',
    exampleScenario: 'Potential seller wants property valuation',
    exampleCustomer: 'Hi, I\'m thinking of selling my house. Can you give me an idea of what it\'s worth?',
    questions: ['Are you looking to buy, sell, or both?', 'What\'s the property address?', 'What\'s your timeline?'],
  },
  {
    id: 'salon',
    name: 'Salons & Spas',
    icon: Scissors,
    shortName: 'Salon',
    avgJobValue: 85,
    missedCalls: 45,
    closeRate: 85,
    description: 'Haircuts, coloring, treatments, and spa services',
    exampleScenario: 'Client wants to book haircut and highlights',
    exampleCustomer: 'I\'d like to book a haircut with partial highlights. Do you have anything this Saturday?',
    questions: ['What service would you like?', 'Who is your preferred stylist?', 'Do you have a preferred day and time?'],
  },
  {
    id: 'dental',
    name: 'Dental Practices',
    icon: Stethoscope,
    shortName: 'Dental',
    avgJobValue: 250,
    missedCalls: 30,
    closeRate: 75,
    description: 'Cleanings, procedures, emergencies, and consultations',
    exampleScenario: 'New patient wants to schedule checkup',
    exampleCustomer: 'I\'m a new patient looking to schedule a cleaning and checkup. Do you take my insurance?',
    questions: ['Are you a new or existing patient?', 'What type of appointment do you need?', 'Do you have dental insurance?'],
  },
  {
    id: 'veterinary',
    name: 'Veterinary Clinics',
    icon: Heart,
    shortName: 'Veterinary',
    avgJobValue: 180,
    missedCalls: 35,
    closeRate: 80,
    description: 'Checkups, treatments, surgeries, and emergencies',
    exampleScenario: 'Pet owner concerned about dog\'s symptoms',
    exampleCustomer: 'My dog hasn\'t been eating for two days and seems lethargic. Can I bring him in?',
    questions: ['What type of pet do you have?', 'What symptoms is your pet showing?', 'How long have you noticed this?'],
  },
  {
    id: 'law_firm',
    name: 'Law Firms',
    icon: Scale,
    shortName: 'Attorney',
    avgJobValue: 1500,
    missedCalls: 18,
    closeRate: 45,
    description: 'Legal consultations, representation, and document services',
    exampleScenario: 'Potential client with legal question',
    exampleCustomer: 'I need to speak with someone about a contract dispute. Do you handle business law cases?',
    questions: ['What type of legal matter is this?', 'Is this an urgent situation?', 'Have you worked with an attorney on this before?'],
  },
  {
    id: 'cleaning',
    name: 'Cleaning Services',
    icon: SprayCan,
    shortName: 'Cleaning',
    avgJobValue: 150,
    missedCalls: 40,
    closeRate: 75,
    description: 'Residential, commercial, deep cleaning, and regular service',
    exampleScenario: 'Homeowner needs one-time deep clean',
    exampleCustomer: 'I need my house deep cleaned before hosting an event this weekend. It\'s a 3-bedroom home.',
    questions: ['Is this a one-time or recurring service?', 'What\'s the approximate square footage?', 'Any special requirements?'],
  },
  {
    id: 'personal_trainer',
    name: 'Personal Trainers & Gyms',
    icon: Dumbbell,
    shortName: 'Personal Trainer',
    avgJobValue: 75,
    missedCalls: 30,
    closeRate: 60,
    description: 'Training sessions, classes, nutrition, and memberships',
    exampleScenario: 'Prospective client wants training info',
    exampleCustomer: 'I\'m looking for a personal trainer. Do you do in-home sessions or just at the gym?',
    questions: ['What are your fitness goals?', 'Do you prefer gym or in-home sessions?', 'What\'s your current activity level?'],
  },
  {
    id: 'photographer',
    name: 'Photographers',
    icon: Camera,
    shortName: 'Photographer',
    avgJobValue: 500,
    missedCalls: 22,
    closeRate: 55,
    description: 'Events, portraits, commercial, and real estate photography',
    exampleScenario: 'Couple inquiring about wedding photography',
    exampleCustomer: 'Hi, I saw your work online. Are you available for a wedding in October? What are your packages?',
    questions: ['What type of photography do you need?', 'What\'s the date and location?', 'Do you have a budget in mind?'],
  },
  {
    id: 'pest_control',
    name: 'Pest Control',
    icon: Shield,
    shortName: 'Pest Control',
    avgJobValue: 180,
    missedCalls: 35,
    closeRate: 80,
    description: 'Inspections, treatments, prevention, and emergency calls',
    exampleScenario: 'Homeowner found termites',
    exampleCustomer: 'I think I found termites in my garage. Can someone come inspect and give me a quote for treatment?',
    questions: ['What type of pest issue are you seeing?', 'Where have you noticed activity?', 'Is this a rental or owned property?'],
  },
];

export const getIndustryById = (id: string): Industry | undefined => {
  return industries.find(i => i.id === id);
};

export const getIndustryByName = (name: string): Industry | undefined => {
  return industries.find(i => i.name === name || i.shortName === name);
};
